# Generated by Django 5.2.1 on 2025-05-15 11:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Имя пункта меню')),
                ('url', models.CharField(max_length=100, unique=True, verbose_name='URL')),
                ('menu_name', models.CharField(max_length=100, verbose_name='Название меню')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='menu.menuitem', verbose_name='Главное меню')),
            ],
            options={
                'verbose_name': 'Вложенное меню',
                'verbose_name_plural': 'Вложенные меню',
                'db_table': 'sub_menu',
            },
        ),
    ]
