# Generated by Django 5.2.1 on 2025-05-14 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MainMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Главное меню')),
            ],
            options={
                'verbose_name': 'Гланое меню',
                'verbose_name_plural': 'Главные меню',
                'db_table': 'main_menu',
            },
        ),
    ]
