# Generated by Django 5.2.1 on 2025-05-14 17:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Вложенное меню')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='URL')),
                ('main_menu', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sub', to='menu.mainmenu', verbose_name='Главное меню')),
            ],
            options={
                'verbose_name': 'Вложенное меню',
                'verbose_name_plural': 'Вложенные меню',
                'db_table': 'sub_menu',
            },
        ),
    ]
